### ISSUE TITLE
Psych 4.0.0 compability fixed but not released

### ISSUE THREAD

**Issue by Hermanlangner** [paper-trail-gem/paper_trail#1363] opened 2022-01-06 14:20 UTC
In september the compatibility with Psych 4.0.0 was fixed but it hasn't been released yet

https://github.com/paper-trail-gem/paper_trail/pull/1338

I am able to temporarily get by with pointing to master branch but it is not a long term solution.

Is there any update on when it will be released?

**Comment by jaredbeck** [comment] 2022-01-11 17:04
Duplicate of https://github.com/paper-trail-gem/paper_trail/issues/1362

**Closed by jaredbeck** 2022-01-11 17:04 UTC
