### ISSUE TITLE
widget.paper_trail.save_with_version not storing meta when custom version table is used

### ISSUE THREAD

**Issue by donatoaz** [paper-trail-gem/paper_trail#1124] opened 2018-07-26 11:19 UTC
Hi everyone!

I am having trouble storing meta data on a custom versions table.

I have pushed a project on github to replicate the issue: [paper_trail_report](https://github.com/donatoaz/paper_trail_report)

ruby 2.5.1
Using paper_trail-association_tracking 1.0.0
Using paper_trail 9.2.0
Using rails 4.2.10

Basically, going into the `rails console` and creating a new record on Servicing model and then manually creating a version does not fill in the meta defined. I tried it without using a custom table (standard versions table with added meta columns) and it worked fine.

```
$ rails c
2.5.1 :001 > s = Servicing.new(status: 'completed', redone: false, completed_by_id: 1, area_id: 1)
 => #<Servicing id: nil, status: "completed", approved_status: nil, redone: false, completed_by_id: 1, area_id: 1, created_at: nil, updated_at: nil>
2.5.1 :002 > s.save!
   (0.1ms)  begin transaction
  SQL (1.5ms)  INSERT INTO "servicings" ("status", "redone", "completed_by_id", "area_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["status", "completed"], ["redone", "f"], ["completed_by_id", 1], ["area_id", 1], ["created_at", "2018-07-26 11:14:15.896615"], ["updated_at", "2018-07-26 11:14:15.896615"]]
   (1.1ms)  commit transaction
 => true
2.5.1 :003 > s.paper_trail.save_with_version
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
   (0.1ms)  begin transaction
  SQL (0.8ms)  INSERT INTO "servicing_versions" ("event", "object", "created_at", "object_changes", "item_id", "item_type") VALUES (?, ?, ?, ?, ?, ?)  [["event", "update"], ["object", "---\nid: 1\nstatus: completed\napproved_status: \nredone: false\ncompleted_by_id: 1\narea_id: 1\ncreated_at: 2018-07-26 11:14:15.896615000 Z\nupdated_at: 2018-07-26 11:14:15.896615000 Z\n"], ["created_at", "2018-07-26 11:14:15.896615"], ["object_changes", "--- {}\n"], ["item_id", 1], ["item_type", "Servicing"]]
   (1.0ms)  commit transaction
 => #<ServicingVersion id: 1, item_type: "Servicing", item_id: 1, event: "update", whodunnit: nil, object: "---\nid: 1\nstatus: completed\napproved_status: \nredo...", object_changes: "--- {}\n", technician_id: nil, area_id: nil, event_name: nil, created_at: "2018-07-26 11:14:15">

```

Additional info:

My model is:

```
class Servicing < ActiveRecord::Base
  has_paper_trail on: [],
                  class_name: 'ServicingVersion',
                  meta: { technician_id: :completed_by_id, area_id: :area_id }
end
```

My custom version model is:

```
# Paper Trail custom class
class ServicingVersion < PaperTrail::Version
  self.table_name = :servicing_versions
  # for pg:
  # self.sequence_name = :servicing_versions_id_seq

  attr_accessor :technician_id, :area_id, :event_name
end
```

**Comment by jaredbeck** [comment] 2018-07-27 00:09
Hi Donato,

Thanks for the bug report. All bug reports are required to use our [bug report template][2]. If you've already got a demo repo it should be easy to use our template. See also our [contributing guide][1].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by jaredbeck** [comment] 2018-07-27 04:58
I'm pretty sure this is a usage question, not a bug report. We don't accept usage questions, as the instructions clearly state, so I'll close this. If anyone wants to help Donato with his usage question, he has also asked the same question on StackOverflow (https://stackoverflow.com/questions/51499530/rails-paper-trail-associations-based-on-versions)

Donato, if I'm wrong and you are trying to report a bug, please open a new issue using the required [bug report template](https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Closed by jaredbeck** 2018-07-27 04:58 UTC
Labels: Need Information

**Comment by donatoaz** [comment] 2018-07-27 10:54
Hi Jared! Thanks for your reply. 

I asked the question on stackoverflow first precisely because I did not want to be a bother, but I do believe it's a bug.

I created the bug report following the format and published as a [gist here](https://gist.github.com/donatoaz/37b926b45a5ba31ef24f4602bd578b31).

**Comment by jaredbeck** [comment] 2018-07-27 17:49
I don't think the [provided gist](https://gist.github.com/donatoaz/37b926b45a5ba31ef24f4602bd578b31) demonstrates a bug. I think your `UserVersion` model is written incorrectly. Remove the `attr_accessor`, it shadows the real `name` column.

```diff
 class UserVersion < PaperTrail::Version
   self.table_name = :user_versions

-  attr_accessor :name
 end
```
