### ISSUE TITLE
Ignore or Skip attributes dynamically is not working

### ISSUE THREAD

**Issue by pgonzaga** [paper-trail-gem/paper_trail#1240] opened 2020-03-31 17:53 UTC
- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gem 'paper_trail', '10.3.1'
gem 'rails', '5.2.3'

ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  has_paper_trail on: %i[update destroy], ignore: { first_name: Proc.new { |obj|  true } }
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    User.create(first_name: "Jane")
    assert_difference(-> { PaperTrail::Version.count },  0) {
      User.update(first_name: "Jane 2")
    }
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`
```

**Comment by tlynam** [comment] 2020-04-26 19:16
Thank you for creating this bug report!  I was able to reproduce the issue with your script and investigating.

**Comment by tlynam** [comment] 2020-04-26 19:33
Hi @pgonzaga, it looks like a version is being created during an update because `updated_at` is being recorded as a change.  Can you confirm this is the case for you?

```
user = User.create(first_name: 'jane')
user.update(first_name: 'jane 2')
user.versions.size
=> 1
user.versions.first.changeset
=> {"updated_at"=>[Sun, 26 Apr 2020 19:31:39 UTC +00:00, Sun, 26 Apr 2020 19:31:41 UTC +00:00]}
```

**Comment by tlynam** [comment] 2020-06-01 01:22
Hi @pgonzaga, were you able to see if a version is being created during an update because `updated_at` is being recorded as a change?

**Comment by guigs** [comment] 2020-06-09 20:37
I also encountered this issue. When using `ignore: %w[foo]` it also ignore changes in `updated_at`, but when using with a proc like `ignore: { foo: Proc.new { |obj| true } }` it does not ignore changes in `updated_at`.

I think this is a surprising behavior, and a bug. I think the cause and possible fix is in the method [`ignored_attr_has_changed?`](https://github.com/paper-trail-gem/paper_trail/blob/21ead888296f022ad63d907b4b15ea598596d1e6/lib/paper_trail/events/base.rb#L150) which doesn't consider ignore attributes with a Proc and it is called by `changed_notably?` method.

**Comment by tlynam** [comment] 2020-06-14 04:39
Thank you @guigs!  Now I understand the issue.  Thank you also for pointing out where to fix this.  I opened #1247 for a fix.

**Closed** 2020-08-16 20:35 UTC
