### ISSUE TITLE
Redefinition of PaperTrail::Version stopped working in v12

### ISSUE THREAD

**Issue by toncid** [paper-trail-gem/paper_trail#1305] opened 2021-04-06 12:44 UTC
Hello,

It seems that the v12 somehow interferes with Rails lazy autoloading in the development environment. The overriding class is no longer concerned. See below the script for more info.

------

Check the following boxes:

- [x] This is not a usage question, this is a bug report
- [ ] This bug can be reproduced with the script I provide below **==> the script cannot be used because it does not rely on autoloading**
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

Due to limited volunteers, we cannot answer *usage* questions. Please ask such
questions on [StackOverflow](https://stackoverflow.com/tags/paper-trail-gem).

Bug reports must use the following template:

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.6.6"
  source "https://rubygems.org"
  gem "activerecord", "5.2.5"
  gem "minitest", "5.14.4"
  gem "paper_trail", "12.0.0", require: false
  gem "sqlite3", "1.4.2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Please use sqlite for your bug reports, if possible.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.bigint :user_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  has_paper_trail meta: {user: ->(item) { item }}

  validates_presence_of :first_name
end

module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern

    belongs_to :user

    validates_presence_of :user
  end
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    assert_difference(-> { PaperTrail::Version.count }, +1) {
      User.create!(first_name: "Jane")
    }
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`

# Running:

D, [2021-04-06T14:36:22.417428 #91222] DEBUG -- :    (0.1ms)  SELECT COUNT(*) FROM "versions"
D, [2021-04-06T14:36:22.420818 #91222] DEBUG -- :    (0.0ms)  begin transaction
D, [2021-04-06T14:36:22.421598 #91222] DEBUG -- :   User Create (0.1ms)  INSERT INTO "users" ("first_name", "created_at", "updated_at") VALUES (?, ?, ?)  [["first_name", "Jane"], ["created_at", "2021-04-06 12:36:22.421102"], ["updated_at", "2021-04-06 12:36:22.421102"]]
D, [2021-04-06T14:36:22.435035 #91222] DEBUG -- :   PaperTrail::Version Create (0.1ms)  INSERT INTO "versions" ("item_type", "item_id", "user_id", "event", "object_changes", "created_at") VALUES (?, ?, ?, ?, ?, ?)  [["item_type", "User"], ["item_id", 1], ["user_id", 1], ["event", "create"], ["object_changes", "---\nid:\n-\n- 1\nfirst_name:\n-\n- Jane\ncreated_at:\n-\n- 2021-04-06 12:36:22.421102000 Z\nupdated_at:\n-\n- 2021-04-06 12:36:22.421102000 Z\n"], ["created_at", "2021-04-06 12:36:22.421102"]]
D, [2021-04-06T14:36:22.439861 #91222] DEBUG -- :    (0.1ms)  commit transaction
D, [2021-04-06T14:36:22.440312 #91222] DEBUG -- :    (0.1ms)  SELECT COUNT(*) FROM "versions"
.

Finished in 0.025732s, 38.8621 runs/s, 38.8621 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

```

------

The script runs well, but this is due to avoided autoloading (`PaperTrail::Version` is defined in the same script).

The problem is with Rails when `PaperTrail::Version` is redefined in another file (see: https://github.com/paper-trail-gem/paper_trail/blob/v12.0.0/README.md#5b2-item-association). This no longer works in development where autoloading is lazy.

Any advice?

**Comment by toncid** [comment] 2021-04-06 15:40
For some reason, the default class from the gem is never overridden by our code in v12:

**v11.1.0**
```
Module.const_source_location("PaperTrail::Version")
"/home/tonci/dev/myapp/app/models/paper_trail/version.rb"
```

**v12.0.0**
```
Module.const_source_location("PaperTrail::Version")
"/home/tonci/.rvm/gems/ruby-2.6.6/gems/paper_trail-12.0.0/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb"
```

**Comment by StanBright** [comment] 2021-04-07 07:38
Hey @toncid, thanks for sharing your experience. I'm just chiming in that I'm fighting the same issue... without much success. I tried a few things but couldn't make it work. 

I reverted back to to `v11.1`, until there's some clarity what's the issue here ¯\_(ツ)_/¯

**Comment by toncid** [comment] 2021-04-07 07:44
@StanBright Thanks for the follow-up and testing in the production mode. We have tried a few different approaches to circumvent the problem, none of them successful, so reverting to v11.1 was also the only option left.

**Comment by criess** [comment] 2021-04-09 07:39
I can confirm the issue, also i have no resolution. On our projects we go with a lower version of papertrail for now.

**Comment by tlynam** [comment] 2021-04-12 07:00
Thank you for opening this and for everyone providing all of the extra details.  Can confirm this issue.  We recently changed loading in https://github.com/paper-trail-gem/paper_trail/pull/1281
I'm trying to understand the issue.  It's interesting that this appears to work with Rails 6 and `zeitwerk` enabled.

**Comment by tlynam** [comment] 2021-04-12 07:59
It seems like it could potentially work if we move the overridden `Version ` class into an initializer.  I'm curious what you think @jaredbeck?

**Comment by jaredbeck** [comment] 2021-04-12 17:07
Hi y'all. Thanks for the report. I tried to reproduce this in a new rails app (6.1) but no luck.

```plain
bin/rails console
Loading development environment (Rails 6.1.3.1)
PaperTrail.gem_version
=> #<Gem::Version "12.0.0">
Module.const_source_location("PaperTrail::Version")
=> ["redacted/pt_issue_1305/app/models/paper_trail/version.rb", 2]
PaperTrail::Version.new.is_a?(PaperTrail::VersionConcern)
=> true
```

What am I missing?

**Comment by tlynam** [comment] 2021-04-12 17:11
We can reproduce in Rails 6.1 by enabling classic mode `config.autoloader = :classic`

**Comment by jaredbeck** [comment] 2021-04-12 17:23
> We can reproduce in Rails 6.1 by enabling classic mode config.autoloader = :classic

Thanks Todd. With that setting, I can reproduce the issue:

```
Module.const_source_location("PaperTrail::Version")
=> ["redacted/paper_trail/frameworks/active_record/models/paper_trail/version.rb", 13]
```

[Classic mode is deprecated](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#classic-mode-is-deprecated), but I'd like PT to support it as long as is practical. Contributions are welcome. If there are practical workarounds, let's document them.

In the changelog, I will reclassify #1281 as a breaking change.

**Comment by tlynam** [comment] 2021-04-12 18:01
Hi @toncid, @StanBright, @criess, does it work if you move the overridden `Version` class into an initializer?

**Comment by jaredbeck** [comment] 2021-04-12 18:55
You might also want to play around with adding a `require_dependency` in your `app/models/paper_trail/version.rb`.

**Comment by fsateler** [comment] 2021-05-19 15:17
This is happening because the new railtie is requiring the active_record framework: https://github.com/paper-trail-gem/paper_trail/pull/1281/files#diff-f226b8d714b180354bcadd32e8b0f55afb2e4d9e2c639c28bcf248aba53b38e0R26 , and the previous engine didn't. The AR framework in turn requires the model class. Apparently using AR-only PT never supported overriding the Version class. (possibly because it doesn't make much sense. Who is doing the autoloading if not rails?)

I have worked around this by adding this in my PT initializer:

```ruby
module PaperTrail
  remove_const :Version
end
```

I believe the proper fix is to not require the Version model, but to keep adding the autoload path. Here is a StackOverflow answer suggesting how to do it: https://stackoverflow.com/a/6394946 . So maybe something like moving the `require 'paper_trail/frameworks/active_record/models/paper_trail/version.rb'` out of the active_record framework, and add an initializer that preserves the autoload mangling from 11.1 .

**Comment by jaredbeck** [comment] 2021-05-20 16:03
Thanks everyone for a productive discussion. 

> Classic mode is deprecated, but I'd like PT to support it as long as is practical. Contributions are welcome. If there are practical workarounds, let's document them.

I'll close this for now with the understanding that our preferred solution is zeitwerk.

```diff
- config.autoloader = :classic # deprecated
+ config.autoloader = :zeitwerk
```

PRs welcome.

**Closed by jaredbeck** 2021-05-20 16:03 UTC

**Comment by fsateler** [comment] 2021-05-20 16:45
Sorry for not mentioning this. I'm seeing the error with the zeitwerk loader.

**Comment by jnimety** [comment] 2021-05-20 16:46
Hmmmm, we're using zeitwerk and ran into this issue. However, we've solved it by creating a new class with our additions (`PaperTrail::ApplicationVersion`) that inherits from `PaperTrail::Version` and configuring our models to use that class for versioning.

**Comment by jaredbeck** [comment] 2021-05-20 17:52
> Hmmmm, we're using zeitwerk and ran into this issue. However, we've solved it by creating a new class with our additions (`PaperTrail::ApplicationVersion`) that inherits from `PaperTrail::Version` and configuring our models to use that class for versioning.

I like the sound of that, Joel. You might also try `include VersionConcern` if you prefer that over inheritance. You might want to inherit from `ApplicationRecord`, for example.

```
class ApplicationVersion < ApplicationRecord
  include PaperTrail::VersionConcern
end
```

I haven't tested the above, and I don't use [Custom Version Classes](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes) personally, so I'd warmly welcome documentation PRs from people who do.

**Comment by jnimety** [comment] 2021-05-20 18:37
Well, I spoke too soon. That change worked just fine in rails console but completely blew up our spec suite (specs won't event run because of an error during setup). I'll report back after I know more.

**Comment by jnimety** [comment] 2021-05-20 18:45
@jaredbeck your `include PaperTrail::VersionConcern` solution seems to work but I need to do more testing to confirm. Are we losing anything from `PaperTrail::Version` when we do it that way?

**Comment by istvan-ujjmeszaros** [comment] 2022-05-20 21:23
Hey guys, why is this issue closed? I am still experimenting the same and I couldn't make any of the workarounds work. Maybe I am doing something wrong, that is our custom module which is getting ignored when upgrading from `v11.1.0` to `v12.3.0`:
```ruby
module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern
    belongs_to :user, foreign_key: :whodunnit, optional: true
  end
end
```

**Comment by weezing** [comment] 2022-12-07 08:13
@istvan-ujjmeszaros I was able to override this bug by defining `Version` model in `models` folder and inherit from `PaperTrail::Version` to have access to such methods as `changeset`

Works like a charm!

```ruby
# frozen_string_literal: true

class Version < PaperTrail::Version
  belongs_to :item, polymorphic: true
  belongs_to :user
end

```

**Comment by AdrienGiboire** [comment] 2023-03-22 10:29
March 2023: I can report this issue to be current still running Rails 6.1 with Zeitwerk and PT 14.

**Comment by AdrienGiboire** [comment] 2023-03-22 11:30
@weezing Inheritance only works if you work from the item and up, but is useless if your starting point is `PaperTrail` as in:

```ruby
Contract.new.versions # works
# versus
PaperTrail::Version.includes(:item).where(item_type: 'Contract').order(created_at: :desc) # does not work
```

**Comment by AdrienGiboire** [comment] 2023-03-22 11:37
I have tried @thebravoman solution and it works.

Create an initializer that requires our custom model.

**Comment by noahfpf** [comment] 2025-02-28 22:23
Regarding the fix suggested by @fsateler, which is the only one that has worked for us: as of Rails 7.2 and PaperTrail 16.0.0, we also now need to load `PaperTrail::Version` before undefining it.

So this works for us:

```ruby
# config/initializers/papertrail.rb
require 'paper_trail/frameworks/active_record/models/paper_trail/version'

module PaperTrail

  remove_const :Version

end
```

```ruby
# app/models/paper_trail/version.rb
module PaperTrail
  class Version < ApplicationRecord # or ActiveRecord::Base

    include PaperTrail::VersionConcern

    # our custom code
  end
end
```

But this feels very hacky, and I wish there was a better solution to adding custom logic to the `Version` model.
